name: HartzAttackUtil
version: '1.0-SNAPSHOT'
main: app.goldbach.hartzAttackUtil.HartzAttackUtil
api-version: '1.21'
commands:
  command:
    description: "Befehl zur Interaktion mit dem HartzAttack Spawn"
    usage: "/hspawn <tp|get|set>"
    permission: hartzattack.hspawn
    permission-message: "Du hast nicht die benötigten Rechte für diesen Befehl"
permissions:
  hartzattack.hspawn:
    description: "Grundpermission für /hspawn"
    default: op
  hartzattack.spawn.tp:
    description: "Erlaubt /hspawn tp"
    default: op
  hartzattack.spawn.set:
    description: "Erlaubt /hspawn set"
    default: op
  hartzattack.spawn.get:
    description: "Erlaubt /hspawn get"
    default: op