name: HartzAttackUtil
version: '1.0-SNAPSHOT'
main: app.goldbach.hartzAttackUtil.HartzAttackUtil
api-version: '1.21'
commands:
  hspawn:
    description: "Befehl zur Interaktion mit dem HartzAttack Spawn"
    usage: "/hspawn <tp|get|set>"
    permission: hartzattack.spawn
    permission-message: "Du hast nicht die benötigten Rechte für diesen Befehl"
  helytra:
    description: "Befehl zur Interaktion mit Spieler-Spawn-Elytren"
    usage: "/helytra <height|remove>"
    permission: hartzattack.elytra
permissions:
  hartzattack.spawn:
    description: "Grundpermission für /hspawn"
    default: op
  hartzattack.spawn.tp:
    description: "Erlaubt /hspawn tp"
    default: op
  hartzattack.spawn.set:
    description: "Erlaubt /hspawn set"
    default: op
  hartzattack.spawn.get:
    description: "Erlaubt /hspawn get"
    default: op
  hartzattack.elytra:
    description: "Grundpermission für /helytra"
    default: op
  hartzattack.elytra.height:
    description: "Erlaubt /helytra height <height>"
    default: op
  hartzattack.elytra.remove:
    description: "Erlaubt /helytra remove <player>"
    default: op